### ISSUE TITLE
Changes in the style 

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Calculator-using-HTML-CSS-JS#10]
Make it more attractive and user-friendly with your CSS skills.

**Comment by Harrshhpattell** [comment]
I want to work on it. **Can u assign it to me**

**Comment by Ctoic** [comment]
You can contribute it has a Hactoberfest label.  I will add the label before merging it.

**Comment by Harrshhpattell** [comment]
can u assign me 😅

**Comment by Ctoic** [comment]
Yeah sure

**Comment by Harrshhpattell** [comment]
I'm excited to share the revamped design of the page! 🎨✨ 
I've worked on making it more attractive and user-friendly. 

![image](https://github.com/Ctoic/Calculator-using-HTML-CSS-JS/assets/102842153/247e8193-8583-48ab-b29f-3bd12d83595f)

**Comment by Ctoic** [comment]
Wow, it looks amazing. I will merge it with the main repo. Thanks for your contribution happy coding ❤️

**Comment by Harrshhpattell** [comment]
Thank you 😍

can u close this issue.....
