### ISSUE TITLE
Change background Color 

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Calculator-using-HTML-CSS-JS#18]
I want the app to change it's background color when we calculate Expressions.

**Comment by Mahek-05** [comment]
Can you explain this please. Like when the user starts typing numbers the background area color should change?

**Comment by Ctoic** [comment]
The user will write any expression like 2+3 and when he hits the "=" button, the background color should change.

**Comment by Ctoic** [comment]
Is it clear now ?

**Comment by Mahek-05** [comment]
yes clear. Ok I can do this . Assign it to me.

**Comment by Ctoic** [comment]
Great I will assign it to you best of luck 🌟  Happy Coding

**Comment by Mahek-05** [comment]
@Ctoic I have implemented this. Please review and merge.

**Comment by Ctoic** [comment]
Okay I will review and merge it soon. Thanks for contribution

**Comment by Mahek-05** [comment]
OK @Ctoic Tell me if you wish to see any changes in it.

**Comment by Ctoic** [comment]
I can see it changes color when we hit the '=' sign but can you change the functionality that the permanent background color changes on each Calculation? Like First it's purple next blue then green and so on . Can you do it?

**Comment by Mahek-05** [comment]
Yes, I can. 
Starting to implement it.

**Comment by Ctoic** [comment]
Great Keep going 👍🏼

**Comment by Mahek-05** [comment]
@Ctoic Hey it is done. Check it.

**Comment by Ctoic** [comment]
Okay Great 👍🏼 lemme check it first then I will merge it.

**Comment by Ctoic** [comment]
Wow, It looks Amazing. It is exactly what I was expecting

**Comment by Mahek-05** [comment]
Thanku so much. Glad u liked it.

**Comment by Ctoic** [comment]
Thank you for your contributions, Keep it up
