### ISSUE TITLE
Add Scientific Calculation Options 

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Calculator-using-HTML-CSS-JS#19]
As the current version of the app only performs the basic functions, it will be great if we include scientific operations.

**Comment by ansh711** [comment]
Please assign it to me , I am willing to do it .

**Comment by Ctoic** [comment]
Okay sure @ansh711 Happy Coding

**Comment by ansh711** [comment]
Thank you sir

**Comment by Ctoic** [comment]
Don't forget to star the repo 😄

**Comment by ansh711** [comment]
sir I have to extend the whole calculator for adding new buttons . that will hamper the designing

**Comment by ansh711** [comment]
what to do sir ?

**Comment by Ctoic** [comment]
Complete the scientific operation task and we will preview how it looks, after that we can look at the design how we can make it better.

**Comment by ansh711** [comment]
okay sir

**Comment by ansh711** [comment]
on it sir

**Comment by Ctoic** [comment]
Thanks @ansh711 for your time. If you have any suggestions we can do that as well.

**Comment by ansh711** [comment]
sir i have done the possible code ... please check that

**Comment by Ctoic** [comment]
Great @ansh711 Have you created a pull request?

**Comment by ansh711** [comment]
changes to create the functions of a scientific calculator #23
please check this

**Comment by Ctoic** [comment]
I just previewed the application and you were right Including more buttons Messed up the Design.

**Comment by ansh711** [comment]
yes sir

**Comment by ansh711** [comment]
the buttons alignment and design will be messed up

**Comment by Ctoic** [comment]
So can you fix this problem after adding the buttons ?

**Comment by ansh711** [comment]
but the task of having the scientific functions are doing great i think

**Comment by Ctoic** [comment]
Did you previewed the application?

**Comment by ansh711** [comment]
yep

**Comment by Ctoic** [comment]
Okay Great should I assign You another task to align the buttons accordingly 😄

**Comment by ansh711** [comment]
yes that will be great help for me , because i am late in hactoberfest , can you provide me 2 pull/merge for this two task ?

**Comment by Ctoic** [comment]
I will assign that task to you. So be responsible and do it on time.  Thanks for your time

**Comment by ansh711** [comment]
ok sure sir

**Comment by ansh711** [comment]
please accept the pull request kindly

**Comment by Ctoic** [comment]
Okay let me review the code Don't worry I will accept it

**Comment by ansh711** [comment]
okay sir, thank you so much

**Comment by Ctoic** [comment]
Can you fix the Design today ?

**Comment by Ctoic** [comment]
With all the scientific operations ?

**Comment by ansh711** [comment]
i will try my best to do that tonight

**Comment by ansh711** [comment]
but i need to change the css file,tags as i need ...... is that okay ?

**Comment by Ctoic** [comment]
Yes, You can change but both your pull requests will be accepted after you do it right 😄 ? Do you dare to take this chance ?

**Comment by ansh711** [comment]
okay I am on it sir

**Comment by Ctoic** [comment]
Okay I have created new issue check that as well I will assign it to you.

**Comment by ansh711** [comment]
I will start coding from 7 o'clock , I need to rest now  ..... please excuse me sir

**Comment by Ctoic** [comment]
Okay great Same here, I'm sitting in front of my Pc From morning. We need rest 👍🏼 Grab a tea or coffee then comeback to work

**Comment by ansh711** [comment]
sir please check and accept my pull request please

**Comment by ansh711** [comment]
There were some issue with the implementation..... From the deepsource ...... I have solved those ...... Please check that

**Comment by Ctoic** [comment]
I have merged your pull request, kindly check and lemme know. Thanks @ansh711 and will see you in future projects.
