### ISSUE TITLE
Add A Fotter 

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Calculator-using-HTML-CSS-JS#20]
Footer Including social links and a GitHub link to the contributors of this project.

**Comment by harsh-p05** [comment]
Hi @Ctoic, Assign me, i would like to work on this project.

**Comment by Ctoic** [comment]
Okay, @harsh-p05 I will assign it to you. Happy Coding :)

**Comment by AvishiJ** [comment]
Hey can u assign this task to me ?

**Comment by Ctoic** [comment]
Already I have assigned it to @harsh-p05, I will assign it to you as well. Best of Luck and Happy Coding

**Comment by Ctoic** [comment]
Hey @AvishiJ there are some conflicts that I'm trying to solve because you have added contribution before the implementation of scientific operations.

**Comment by AvishiJ** [comment]
After implementing scientific calculations ,kindly have a glance at the changes I made. Thank you.

**Comment by Ctoic** [comment]
I have seen your Implementation they are great. but now I cannot merge your pull request because GitHub is not allowing me to do so. It shows notification to resolve the conflicts. Or you can again create a pull request for the updated version.

**Comment by AvishiJ** [comment]
Please notify me when to create a pull request again.

**Comment by Ctoic** [comment]
I have been assigned the task of making scientific calculators responsive. You can create a pull request now we will see if I can merge it or not.
