### ISSUE TITLE
Design Issues 

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Calculator-using-HTML-CSS-JS#24]
After Adding Extra buttons for the Scientific Operations. The Overall design of the Calculator is out of Order. Contributions are welcome.

**Comment by ansh711** [comment]
please assign me this sir

**Comment by Ctoic** [comment]
Happy Coding Again Best Of Luck @ansh711

**Comment by ansh711** [comment]
thank you sir

**Comment by Ctoic** [comment]
You are Doing Great 👍🏼 Now take some rest

**Comment by ansh711** [comment]
back to work sir

**Comment by ansh711** [comment]
sir i have solved the problem but accidentally pushed to the previous issue

**Comment by ansh711** [comment]
please check that sir

**Comment by ansh711** [comment]
please check this changes to create the functions of a scientific calculator #23

**Comment by ansh711** [comment]
sir please check and accept my pull request kindly

**Comment by Ctoic** [comment]
Okay great work. I will merge it soon

**Comment by ansh711** [comment]
There were some issue with the implementation..... From the deepsource ...... I have solved those ...... Please check that

**Comment by Ctoic** [comment]
![Screenshot from 2023-10-22 10-48-18](https://github.com/Ctoic/Calculator-using-HTML-CSS-JS/assets/90936436/74e38686-f733-49ea-8259-c88cc4c699f7)

**Comment by ansh711** [comment]
Yes sir .... Any problem sir ?

**Comment by Ctoic** [comment]
I guess it's not responsive. I have created another issue to make it responsive. If possible you can remove the white strip.

**Comment by ansh711** [comment]
Okay I will remove the white strip

**Comment by ansh711** [comment]
I am now out of my house .... So please give me some time

**Comment by ansh711** [comment]
Responsiveness is really not my forte actually ... I am really sorry about that sir

**Comment by ansh711** [comment]
But if you say I can try

**Comment by Ctoic** [comment]
It's Okay we mess things up and then fix them. Programming is about solving problems. we will try to make it responsive
