### ISSUE TITLE
Responsive Design 

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Calculator-using-HTML-CSS-JS#29]
After the Addition of scientific Notation, it is no longer responsive. I would highly appreciate it if someone solved this issue.

**Comment by mohtasheem135** [comment]
hello bro, I can do this....can you please assign me this task...

**Comment by Ctoic** [comment]
Sure @mohtasheem135

**Comment by Ctoic** [comment]
Best of luck

**Comment by mohtasheem135** [comment]
Getting this error message bro ....

remote: Permission to Ctoic/Calculator-using-HTML-CSS-JS.git denied to mohtasheem135.
fatal: unable to access 'https://github.com/Ctoic/Calculator-using-HTML-CSS-JS.git/': The requested URL returned error: 403

**Comment by mohtasheem135** [comment]
![WhatsApp Image 2023-10-22 at 20 03 37](https://github.com/Ctoic/Calculator-using-HTML-CSS-JS/assets/82079433/655bab52-3f85-4235-8c5f-34e8373287f8)

**Comment by Ctoic** [comment]
It is because the base code changed after you forked the repository.  Fork the current version of repo again and try.

**Comment by Ctoic** [comment]
I have added new issues you can try them as well and I will merge them.

**Comment by mohtasheem135** [comment]
> It is because the base code changed after you forked the repository. Fork the current version of repo again and try.

I don't think that is the issue....There is some kind of permission issue I also don't know exactly the reason but again its showing the same problem.

**Comment by Ctoic** [comment]
Other Contributors are contributing they are not facing any issues @mohtasheem135 but I will look at this again. Hopefully, I will fix it.

**Comment by mohtasheem135** [comment]
I am really sorry bro .....it was actually my mistake
I have made the PR  ....  please use the hactoberfest tag

**Comment by Ctoic** [comment]
I have merged your pull request. Don't forget to star the Repository ⭐
