### ISSUE TITLE
Update Readme and Mange the Directories

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Calculator-using-HTML-CSS-JS#34]
Anyone who is great at documentation can contribute. 
1. Bring all profile of Contributors to readme
2. Include some animations and Images 
You can display your creativity. Get started now

**Comment by naikmubashir** [comment]
Assign me this issue.

**Comment by Ctoic** [comment]
Assigned @naikmubashir go ahead Happy coding  😃

**Comment by Ctoic** [comment]
It will be great if you can add all the contributors Profile in the GitHub readme file.

**Comment by Ctoic** [comment]
Don't forget to star the repo before your pull request.
