### ISSUE TITLE
[BUG] Wrong Answer for FACTORIAL of a number(x!)

### ISSUE THREAD

**Issue by naikmubashir** [Ctoic/Calculator-using-HTML-CSS-JS#37]
The factorial button doesn't calculate the factorial correctly

### Video : 

https://github.com/Ctoic/Calculator-using-HTML-CSS-JS/assets/124430100/5e5e0b7e-4ec4-484e-b461-4946cd33f8b6

**Comment by naikmubashir** [comment]
I would like to work on it.

**Comment by Ctoic** [comment]
Great @naikmubashir  I'm assigning it to you. Thanks for pointing out ❤️

**Comment by Ctoic** [comment]
Star the repository before your pull request ⭐
