### ISSUE TITLE
Enhance Calculator Functionality: Implement "=" on "Enter" Key Press

### ISSUE THREAD

**Issue by K-RD** [Ctoic/Calculator-using-HTML-CSS-JS#48]
### Issue Summary:
I would like to propose an enhancement to the existing calculator functionality on the project. Currently, the calculator performs calculations when the "=" button is clicked. However, it would be user-friendly to also allow the calculation to be executed when the "Enter" or "Return" key on the keyboard is pressed.

### Expected Behavior:
When a user enters an equation and presses the "Enter" or "Return" key on their keyboard, the calculator should perform the calculation, mimicking the functionality of clicking the "=" button.

### Steps to Reproduce:
1. Open the calculator on the project.
2. Enter a mathematical expression (e.g., 2 + 2) into the input field.
3. Press the "Enter" or "Return" key on the keyboard.

### Current Behavior:
At present, pressing the "Enter" or "Return" key does not trigger the calculation. Users are required to click the "=" button manually.

### Suggested Implementation:
To implement this feature, you can use JavaScript to listen for the "Enter" or "Return" key press event when the calculator input field is in focus. When the key is pressed, execute the calculation process as if the "=" button was clicked.

**Comment by Ctoic** [comment]
Ok Great @K-RD if you want to add this functionality I will assign the issue to you. Let me know

**Comment by K-RD** [comment]
Please assign me this issue and  add the necessary tags.

**Comment by K-RD** [comment]
As per the advancement in the project, I don't think there is any need to implement this functionality. Please do let me know your opinions, then will close this issue after discussion.
