### ISSUE TITLE
feat: Redesigning the tic tac toe game giving a refreshing look.

### ISSUE THREAD

**Issue by shivam-sharma-03** [Ctoic/Calculator-using-HTML-CSS-JS#6]
As the title suggests, this issue is regarding the styling. So get your CSS skills to work by improving the design of the overall application (or maybe a part of it)

**Comment by shivam-sharma-03** [comment]
A simple yet interesting design using Html CSS
Please assign this issue under Hacktoberfest 2023.
Thank You.

**Comment by Ctoic** [comment]
I'm really sorry but I  didn't got what you want to do?

**Comment by shivam-sharma-03** [comment]
hey @Ctoic i have just created a pull request that fixes #6 . Please review It and and also please attach Hactoberfest and Hacktoberfest-Accepted labels to the pr.

**Comment by Ctoic** [comment]
OOps really sorry I didn't add the label. Please commit some changes again I will add the labels

**Comment by shivam-sharma-03** [comment]
hey @Ctoic Thank you for merging this PR and there is no problem if you forgot to add label to this pr, please remember it in the next PR.

**Comment by Ctoic** [comment]
Okay @shivam-sharma-03, I will. am Impressed with your CSS skills.  Keep it up 👍🏼

**Comment by Ctoic** [comment]
How to add Hactoberfest and Hacktoberfest-Accepted labels to the pr ?

**Comment by Ctoic** [comment]
Should I add them to the topic section of the repo ?

**Comment by shivam-sharma-03** [comment]
**steps to add label to a repository**:
1.Go to the PR.
2.On the right hand side you will see the labels tab.
3.click on that and type the hactoberfest and hactoberfest-accepted label one by one.
4.If you already don't have these labels then there only you will see the option to create new labels.
5.Create and add them to the repository.

Hope this would help you with the above problem.

**Comment by shivam-sharma-03** [comment]
@Ctoic can you please mention the project that requires flask knowledge, I am confident that i can contribute to that project also.
