### ISSUE TITLE
Improve footer design

### ISSUE THREAD

**Issue by rafiaatiq** [Ctoic/Calculator-using-HTML-CSS-JS#64]
The footer section color does not goes with overall page.
Here are the things we can add to make it look better :
1) change background color of footer
2) instead of using images of social links, we can replace it with icons

overall improvements need to footer section.

**Comment by Ctoic** [comment]
Okay sounds great @rafiaatiq I will assign it to you if you want to contribute ?

**Comment by rafiaatiq** [comment]
Yes, i want to work on it.

**Comment by Ctoic** [comment]
Great Go ahead 👍🏼

**Comment by Ctoic** [comment]
Happy Coding 😃

**Comment by rafiaatiq** [comment]
Thank You for assigning it to me

**Comment by Ctoic** [comment]
Have you registered for HactoberFest ?

**Comment by rafiaatiq** [comment]
No, I randomly found this repo

**Comment by rafiaatiq** [comment]
Do i have to register to contribute in this repository?

**Comment by Ctoic** [comment]
No, It will be good for you to participate in Hacktoberfest. If you have not registered

**Comment by Ctoic** [comment]
You can contribute, and have you contributed before  to open source ?

**Comment by rafiaatiq** [comment]
Okay i will register thank you for guidance. This is my first open source contribution

**Comment by Ctoic** [comment]
Okay Best Of luck
