### ISSUE TITLE
Square root button not working

### ISSUE THREAD

**Issue by lavish-github** [Ctoic/Calculator-using-HTML-CSS-JS#67]
I am not able to use square root button

![image](https://github.com/Ctoic/Calculator-using-HTML-CSS-JS/assets/140691026/794618bd-5718-4dab-b77f-4bdc33afb5ac)

Neither it is working in any mathematical expression

**Comment by Ctoic** [comment]
OK, I have assigned the issue to you.

**Comment by Ctoic** [comment]
star the repo before I merge it with the main brach.

**Comment by ankitkumar0622** [comment]
Hi @lavish-github ,Can you please assign me this task.

**Comment by lavish-github** [comment]
@Ctoic, I have already starred the repo.

Hello @ankitkumar0622, I have already made a PR regarding this bug. You can look for other issues or maybe work on [this](https://github.com/Ctoic/Calculator-using-HTML-CSS-JS/issues/38) functionality.

Thanks
